### ISSUE TITLE
No such host is known "android-sdk.is.com"

### ISSUE THREAD

**Issue by zenow92** [XieSandi/Yodo1-MAS-Integration-testing#1]
I am getting this error while building project 
No such host is known "android-sdk.is.com"
I have tried some other ways provided on Yodo1 official site but there i am also getting "resources linking failed error".
what wrong with this.

**Comment by XieSandi** [comment]
Hmm. I'm not yodo1's developer
So, I can't give the best answer.

But, I'm my experience handle your mas in my game. Sometimes the MAS CDN link is broken

So you can't fetch the mediation file into your project

The best solution is to contact the yodo1 team about your problem. 

If you are having a contract with yodo1 you can easily contact them via the whatsapp number that they provide

**Comment by zenow92** [comment]
i do not have Yodo1 team Contact no. Can you provide ?
& this project is functional at your end.

**Comment by XieSandi** [comment]
I'm sorry that I cant provide the contact number because of the NDA.
but, you can contact them via their website [https://www.yodo1.com/contact-us]()

also, I don't get what you mean about "this project is functional at your end."

**Comment by XieSandi** [comment]
PS.
I'm not a Yodo1 developer and didn't affiliate with them.
But a few months ago, I worked for a company that has cooperated with yodo1
and this repository is a testing project that I use to integrate the game from the company with MAS API. (i will delete this repo in 2022 tough)

**Comment by XieSandi** [comment]
btw, you can open issue in their account for further question [https://github.com/Yodo1Games]()
